/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRoutingRouteImport } from './routes/_app/routing'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppAdsRouteImport } from './routes/_app/ads'
import { Route as ApiAuthActionRouteImport } from './routes/api.auth.$action'
import { Route as ApiAnalyticsResourceRouteImport } from './routes/api.analytics.$resource'
import { Route as ApiInternalAnalyticsBitrixSyncRouteImport } from './routes/api.internal.analytics.bitrix-sync'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutingRoute = AppRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdsRoute = AppAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthActionRoute = ApiAuthActionRouteImport.update({
  id: '/api/auth/$action',
  path: '/api/auth/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsResourceRoute = ApiAnalyticsResourceRouteImport.update({
  id: '/api/analytics/$resource',
  path: '/api/analytics/$resource',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAnalyticsBitrixSyncRoute =
  ApiInternalAnalyticsBitrixSyncRouteImport.update({
    id: '/api/internal/analytics/bitrix-sync',
    path: '/api/internal/analytics/bitrix-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ads': typeof AppAdsRoute
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/leads': typeof AppLeadsRoute
  '/routing': typeof AppRoutingRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/analytics/$resource': typeof ApiAnalyticsResourceRoute
  '/api/auth/$action': typeof ApiAuthActionRoute
  '/api/internal/analytics/bitrix-sync': typeof ApiInternalAnalyticsBitrixSyncRoute
}
export interface FileRoutesByTo {
  '/ads': typeof AppAdsRoute
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/leads': typeof AppLeadsRoute
  '/routing': typeof AppRoutingRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AppIndexRoute
  '/api/analytics/$resource': typeof ApiAnalyticsResourceRoute
  '/api/auth/$action': typeof ApiAuthActionRoute
  '/api/internal/analytics/bitrix-sync': typeof ApiInternalAnalyticsBitrixSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ads': typeof AppAdsRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/routing': typeof AppRoutingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/api/analytics/$resource': typeof ApiAnalyticsResourceRoute
  '/api/auth/$action': typeof ApiAuthActionRoute
  '/api/internal/analytics/bitrix-sync': typeof ApiInternalAnalyticsBitrixSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/contacts'
    | '/inbox'
    | '/leads'
    | '/routing'
    | '/settings'
    | '/api/health'
    | '/api/analytics/$resource'
    | '/api/auth/$action'
    | '/api/internal/analytics/bitrix-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ads'
    | '/contacts'
    | '/inbox'
    | '/leads'
    | '/routing'
    | '/settings'
    | '/api/health'
    | '/'
    | '/api/analytics/$resource'
    | '/api/auth/$action'
    | '/api/internal/analytics/bitrix-sync'
  id:
    | '__root__'
    | '/_app'
    | '/_app/ads'
    | '/_app/contacts'
    | '/_app/inbox'
    | '/_app/leads'
    | '/_app/routing'
    | '/_app/settings'
    | '/api/health'
    | '/_app/'
    | '/api/analytics/$resource'
    | '/api/auth/$action'
    | '/api/internal/analytics/bitrix-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAnalyticsResourceRoute: typeof ApiAnalyticsResourceRoute
  ApiAuthActionRoute: typeof ApiAuthActionRoute
  ApiInternalAnalyticsBitrixSyncRoute: typeof ApiInternalAnalyticsBitrixSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routing': {
      id: '/_app/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AppRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ads': {
      id: '/_app/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AppAdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$action': {
      id: '/api/auth/$action'
      path: '/api/auth/$action'
      fullPath: '/api/auth/$action'
      preLoaderRoute: typeof ApiAuthActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/$resource': {
      id: '/api/analytics/$resource'
      path: '/api/analytics/$resource'
      fullPath: '/api/analytics/$resource'
      preLoaderRoute: typeof ApiAnalyticsResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/analytics/bitrix-sync': {
      id: '/api/internal/analytics/bitrix-sync'
      path: '/api/internal/analytics/bitrix-sync'
      fullPath: '/api/internal/analytics/bitrix-sync'
      preLoaderRoute: typeof ApiInternalAnalyticsBitrixSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdsRoute: typeof AppAdsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppRoutingRoute: typeof AppRoutingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdsRoute: AppAdsRoute,
  AppContactsRoute: AppContactsRoute,
  AppInboxRoute: AppInboxRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppRoutingRoute: AppRoutingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAnalyticsResourceRoute: ApiAnalyticsResourceRoute,
  ApiAuthActionRoute: ApiAuthActionRoute,
  ApiInternalAnalyticsBitrixSyncRoute: ApiInternalAnalyticsBitrixSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
